"""add week to staff preferred days

Revision ID: b651b9c23c9a
Revises: c99465753317
Create Date: 2026-07-23 13:43:41.257779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b651b9c23c9a'
down_revision: Union[str, Sequence[str], None] = 'c99465753317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written rather than autogenerated: the table's old UNIQUE(staff_id, day_of_week)
    # is inline/anonymous (see app/models/rule.py's docstring on SQLite's limited ALTER-time
    # constraint support), so a full rename-recreate-copy-drop is used instead of a bare
    # ADD COLUMN + ADD CONSTRAINT, which autogenerate can't reliably diff for SQLite anyway.
    op.execute("ALTER TABLE staff_preferred_days RENAME TO staff_preferred_days_old")
    op.create_table(
        "staff_preferred_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["staff_id"], ["staff.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("staff_id", "week", "day_of_week"),
    )
    # Preserve current behavior for every existing preference (previously applied to both
    # weeks of the fortnight — see CONTEXT.md's Preferred Days entry) by duplicating each row
    # into both week 0 and week 1, rather than picking one arbitrarily.
    op.execute(
        "INSERT INTO staff_preferred_days (staff_id, week, day_of_week) "
        "SELECT staff_id, 0, day_of_week FROM staff_preferred_days_old"
    )
    op.execute(
        "INSERT INTO staff_preferred_days (staff_id, week, day_of_week) "
        "SELECT staff_id, 1, day_of_week FROM staff_preferred_days_old"
    )
    op.execute("DROP TABLE staff_preferred_days_old")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE staff_preferred_days RENAME TO staff_preferred_days_new")
    op.create_table(
        "staff_preferred_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["staff_id"], ["staff.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("staff_id", "day_of_week"),
    )
    # Collapses back to one row per (staff_id, day_of_week); arbitrarily keeps week 0's rows
    # since a week-specific preference has no lossless single-week representation.
    op.execute(
        "INSERT INTO staff_preferred_days (staff_id, day_of_week) "
        "SELECT DISTINCT staff_id, day_of_week FROM staff_preferred_days_new WHERE week = 0"
    )
    op.execute("DROP TABLE staff_preferred_days_new")
