"""add name to rules

Revision ID: c99465753317
Revises: 311cc8c67351
Create Date: 2026-07-22 17:55:34.449275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99465753317'
down_revision: Union[str, Sequence[str], None] = '311cc8c67351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing Rules predate the name field and have nothing sensible to backfill it with.
    # SQLite also rejects ADD COLUMN ... NOT NULL outright on a non-empty table (no DEFAULT
    # clause given), so clearing the table first is required, not just a data-hygiene choice.
    op.execute("DELETE FROM rules")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'name')
    # ### end Alembic commands ###
