"""add name to rules

Revision ID: c99465753317
Revises: 311cc8c67351
Create Date: 2026-07-22 17:55:34.449275

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c99465753317"
down_revision: str | Sequence[str] | None = "311cc8c67351"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing Rules predate the name field and have nothing sensible to backfill it with,
    # but deleting them outright would silently drop a practice's configured rostering
    # constraints and orphan any roster_violations.rule_id pointing at them. Add the column
    # nullable, backfill a placeholder, then rebuild the table to make it NOT NULL — SQLite
    # has no ALTER COLUMN, and also rejects ADD COLUMN ... NOT NULL on a non-empty table
    # without a DEFAULT, so a plain add_column can't get there in one step either way.
    op.add_column("rules", sa.Column("name", sa.String(), nullable=True))
    op.execute("UPDATE rules SET name = 'Untitled rule #' || id WHERE name IS NULL")

    # rules is itself an FK target (roster_violations.rule_id), and SQLite's RENAME TABLE
    # rewrites *other* tables' FK definitions to follow the renamed table. Renaming rules
    # away first (the more obvious approach) would leave roster_violations referencing the
    # temporary name, then dangling once that table is dropped. Building the replacement
    # under a temporary name and renaming *it* into place at the end avoids ever renaming
    # the table other rows still reference.
    op.create_table(
        "rules_new",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "rule_type",
            sa.Enum("minimum_count", "eligibility_restriction", name="ruletype"),
            nullable=False,
        ),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.Column("minimum_count", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(rule_type = 'eligibility_restriction' AND tag_id IS NOT NULL "
            " AND building_id IS NULL AND minimum_count IS NULL) "
            "OR "
            "(rule_type = 'minimum_count' AND minimum_count >= 1 "
            " AND ((building_id IS NOT NULL AND tag_id IS NULL) "
            "      OR (building_id IS NULL AND tag_id IS NOT NULL)))",
            name="ck_rule_shape",
        ),
        sa.ForeignKeyConstraint(["building_id"], ["buildings.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"]),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "INSERT INTO rules_new (id, name, rule_type, role_id, building_id, tag_id, minimum_count) "
        "SELECT id, name, rule_type, role_id, building_id, tag_id, minimum_count FROM rules"
    )
    op.execute("DROP TABLE rules")
    op.execute("ALTER TABLE rules_new RENAME TO rules")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rules", "name")
    # ### end Alembic commands ###
